# Site settings
title: Silence of Ninja
header-img: img/home-bg.jpg
email: antonevane@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/devblog"
url: "http://silenceof.ninja"
twitter_username: anton_evane
github_username:  antonevane
facebook_username:  ""

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# blog silenceofninja
# localhost is localconfiguration
#disqus_name: localhost
disqus_name: silenceofninja